---
title: "Taller Interpolación"
author: "Sebastian Roberts, Camilo Ruiz, Alex Barreto"
date: "06/09/2019"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

#2.  Construya un polinomio de grado tres que pase por:(0, 10),(1, 15),(2, 5) y que la tangente sea igual a 1 en x0
    
require(pracma) 
x = c(0,1,2)
y= c(10,15,5)
xs <- seq(0, 2, by = 1)
pp <- cubicspline(x, y)
ppfun <- function(xs) ppval(pp, xs)
curve(ppfun(x),from=0,to=3,xlab = "x", ylab = "f(x)", main = "Grafica Segundo Punto")


#4. Con la función f(x) = lnx construya la interpolación de diferencias divididas en x0 = 1; x1 = 2 y estime el error en [1;2]

newtonInterpolacion = function(x, y, a) {
  n = length(x)
  A = matrix(rep(NA, times = n^2), nrow = n, ncol = n)
  A[,1] = y
  for (k in 2:n) {
    A[k:n, k] = (A[k:n, k-1] - A[(k-1):(n-1), k-1] ) / (x[k:n] - x[1:(n-k+1)])
  }
  # Imprimir matriz de diferencias divididas
  print(A)
  # Evaluar
  smds = rep(NA, length = n)
  smds[1] = 1 #x = x[1],..., x[n] pues n = length(x)
  for (k in 2:n) {
    smds[k] = (a - x[k-1])*smds[k-1] # hasta x[n-1]
  }
  return(sum(diag(A)*smds) )
}
arithmetic.mean <- function(x) {return(sum(x)/length(x))}
f = function(x) log(x)
x1 = c(1,2)
logaritmo = f(x1)
#Traza de la función Logaritmica
plot(x1,logaritmo,type="l", col="blue",xlab = "x", ylab = "f(x)", 
     main = "Ln e interpolación")
#Traza de la recta
curve(log,1,2,add = T, col="red")
x2 = seq(1,2,by=0.1)
interpolados = c()
for (i in x2) {
  interpolados = c(interpolados,newtonInterpolacion(x1,logaritmo,i));
}
# Tabla de Interpolados
print(interpolados)
reales = f(x2)
errores = c()
for (i in 1:length(reales)) {
  errores = c(errores,abs(reales[i]-interpolados[i]))  
}
# Tabla de errores
print(errores)
#Promedio de error 
prom = arithmetic.mean(errores)
print(prom)


#5. Utilice la interpolación de splines cúbicos para el problema de la mano y del perrito

---
library(polynom)
library(PolynomF)
#Puntos rojos: puntos para graficar la mano
x=c(14.65, 14.71, 14.6, 14.8, 15.2, 15.6, 15.7, 17.0, 17.6, 17.52, 17.3, 16.8, 
    15.4, 14.83, 14.4, 14.5, 15.0, 15.1, 15.0, 14.9, 14.6, 14.3, 14.0, 13.9, 
    13.8, 13.5, 13.1, 13.0, 13.3, 13.2, 13.1, 12.9, 12.4, 11.9, 11.7, 11.6, 
    11.3, 10.9, 10.7, 10.6, 10.6, 10.1, 9.7, 9.4, 9.3, 9.6, 9.9, 10.1, 10.2, 
    10.3, 9.10, 8.6, 7.5, 7.0, 6.7, 6.6, 7.70, 8.00, 8.10, 8.40,9.20, 9.30, 
    10, 10.2, 10.3, 10.0, 9.50)                                                                                                       
y=c(14.7, 14.33, 13.4, 12.33, 11.0, 10.5, 10.22, 8.20, 7.10, 6.70, 6.60, 6.80,
    8.30, 8.80, 9.30, 8.80, 6.30, 5.50, 5.00, 4.70, 4.60, 4.50, 4.90, 5.40, 
    5.80, 6.90, 8.20, 7.60, 5.80, 4.50, 4.30, 3.90, 4.20, 5.70, 7.00, 7.90,
    8.20, 7.30, 6.70, 5.50, 5.10, 4.60, 4.7, 5.0, 5.5, 7.2, 7.8, 8.60, 9.40, 
    10.0, 10.7, 9.9, 9.0, 9.1, 9.3, 9.7, 11.7, 12.3, 12.5, 13.0,13.91, 14.9, 
    16, 16.4, 16.8, 10.7, 11.0)     
length(x)
plot(x,y, pch=19, cex=0.5, col = "red", asp=1,xlab="X", ylab="Y", main="Mano ")

#Puntos cafés: puntos mínimos para grafica la mano
x2=c(14.6, 15.2, 17.0, 17.3, 16.8, 14.4, 15.0, 14.6, 13.9, 13.1, 13.3, 
     12.9, 11.9, 11.3, 10.6, 10.1, 9.3, 10.0, 9.10, 8.6,7.5, 7.0, 6.6, 8.10, 10.3)
y2=c(14.7, 11.0, 8.20, 6.70, 6.80, 9.30, 6.30, 4.60, 5.40, 8.20, 5.80,
     3.90, 5.70, 8.20, 5.50, 4.60, 5.50, 10.7,10.7, 9.9,9.0, 9.1, 9.7, 12.5, 16.8)
length(x2)
par(new=T)
plot(x2,y2, pch=19, cex=0.9, col = "brown", asp=1,xlab="X", ylab="Y", main="Mano ")

cubicSpline<- function(x,y){
   a=rep(y)
   n=length(x)
   h<-(c(x,0)-c(0,x))[2:n]
   alph<-(3/c(1,h,1,1)*(c(a,1,1) - c(1,a,1)) - 3/c(1,1,h,1)*(c(1,a,1)-c(1,1,a)))[3:n]
   A <- c(1,rep(0,times=n-1))
   for (i in 1:(n-2)) {
     A <- rbind(A,c( rep(0,times=i-1) , c(h[i],2*(h[i]+h[i+1]),h[i+1]) , rep(0,times=n-i-2) ) )
   }
   A <- rbind(A,c(rep(0,times=n-1),1))
   b <- c(0,alph,0)
   c <- solve(A, b)
   b <- ((c(a,0) - c(0,a))/c(1,h,1) - c(1,h,1)/3*(c(c,0) + 2*c(0,c)))[2:n]
   d <- ((c(c,0) - c(0,c))/(3*c(1,h,1)))[2:n]
   ans = rbind(a[1:n-1],b,c[1:n-1],d)
}

dibujar<-function(x,y){
   t = 1:length(x)
   sx = cubicSpline(t,x)
   sy = cubicSpline(t,y)
   for (i in 1:(length(t)-1)) {
     dat<- data.frame(t=seq(t[i],t[i+1], by=0.1) )
     fx <- function(x) (sx[1,i] + sx[2,i]*(x-t[i]) + sx[3,i]*(x-t[i])^2 + sx[4,i]*(x-t[i])^3)
     fy <- function(x) (sy[1,i] + sy[2,i]*(x-t[i]) + sy[3,i]*(x-t[i])^2 + sy[4,i]*(x-t[i])^3)
     dat$y=fy(dat$t)
     dat$x=fx(dat$t)
     points(dat$x,dat$y,type='l', col='pink',lwd=3)
   }
 }

dibujar(x2,y2)


#8. Considere el comportamiento de gases no ideales se describe a menudo con la ecuación virial de estado.En la siguiente figura se muestra como se distribuye la variable B a lo largo de la temperatura
#a) Determine un polinomio interpolante para este caso
#b) Utilizando el resultado anterior calcule el segundo y tercer coeficiente virial a 450K.
#c) Grafique los puntos y el polinomio que ajusta
#d) Utilice la interpolaci´on de Lagrange y escriba el polinomio interpolante
#e) Compare su resultado con la serie truncada (modelo te´orico), cu´al aproximacion es mejor por qué?
require(pracma)

#Método Lagrange Baricentrico
lagrangeB <- function(x)
{
  n <- length(x)
  return((n+1)^2)
}

#Método diferencias divididas
diferenciasD <- function(x, y, x0) {
  require(rSymPy)
  n <- length(x)
  q <- matrix(data = 0, n, n)
  q[,1] <- y
  f <- as.character(round(q[1,1], 5))
  fi <- ''
  it = 0
  for (i in 2:n) {
    for (j in i:n) {
      q[j,i] <- (q[j,i-1] - q[j-1,i-1]) / (x[j] - x[j-i+1])
      it = it + 1
    }
    fi <- paste(fi, '*(x - ', x[i-1], ')', sep = '', collapse = '')
    
    f <- paste(f, ' + ', round(q[i,i], 5), fi, sep = '', collapse = '')
  }
  
  x <- Var('x')
  sympy(paste('e = ', f, collapse = '', sep = ''))
  approx <- sympy(paste('e.subs(x, ', as.character(x0), ')', sep = '', collapse = ''))
  
  return(list('Approximation from Interpolation'=as.numeric(approx),'Multiplications'=it))
}
#Punto 2
x2 <- c(100,200,300,400,500,600)
y2 <- c(-160,-35,-4.2,9,16.9,21.3)
barylag (x2,y2,c(450))
lagrangeB(x2)
diferenciasD(x2,y2,450)
